CREATE TABLE "test__CV3BasicObs" (
	"GUID" DECIMAL, 
	"ClientVisitGUID" DECIMAL, 
	"ClientGUID" DECIMAL, 
	"OrderGUID" DECIMAL, 
	"MasterGUID" DECIMAL, 
	"ChartGUID" VARCHAR, 
	"ResultItemGUID" VARCHAR, 
	"Status" VARCHAR, 
	"Active" BOOLEAN, 
	"AbnormalityCode" VARCHAR, 
	"ItemName" VARCHAR, 
	"ClusterID" DECIMAL, 
	"Value" VARCHAR, 
	"ReferenceUpperLimit" VARCHAR, 
	"ReferenceLowerLimit" VARCHAR, 
	"UnitOfMeasure" VARCHAR, 
	"TypeCode" VARCHAR, 
	"IsHistory" BOOLEAN, 
	"IsTextual" BOOLEAN, 
	"HasHistory" BOOLEAN, 
	"HasMediaLink" BOOLEAN, 
	"AckStatusNum" DECIMAL, 
	"Entered" TIMESTAMP WITHOUT TIME ZONE, 
	"ArrivalDtm" TIMESTAMP WITHOUT TIME ZONE, 
	"TouchedWhen" TIMESTAMP WITHOUT TIME ZONE, 
	"CreatedWhen" TIMESTAMP WITHOUT TIME ZONE
);
